<?php

/**
 * BaseTitular
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nome
 * @property string $matricula
 * @property date $data_admiss
 * @property date $data_expira
 * @property date $data_nasc
 * @property date $data_renova
 * @property string $estado_civil
 * @property string $sexo
 * @property Doctrine_Collection $Dependentes
 * @property Doctrine_Collection $Atendimentos
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getNome()         Returns the current record's "nome" value
 * @method string              getMatricula()    Returns the current record's "matricula" value
 * @method date                getDataAdmiss()   Returns the current record's "data_admiss" value
 * @method date                getDataExpira()   Returns the current record's "data_expira" value
 * @method date                getDataNasc()     Returns the current record's "data_nasc" value
 * @method date                getDataRenova()   Returns the current record's "data_renova" value
 * @method string              getEstadoCivil()  Returns the current record's "estado_civil" value
 * @method string              getSexo()         Returns the current record's "sexo" value
 * @method Doctrine_Collection getDependentes()  Returns the current record's "Dependentes" collection
 * @method Doctrine_Collection getAtendimentos() Returns the current record's "Atendimentos" collection
 * @method Titular             setId()           Sets the current record's "id" value
 * @method Titular             setNome()         Sets the current record's "nome" value
 * @method Titular             setMatricula()    Sets the current record's "matricula" value
 * @method Titular             setDataAdmiss()   Sets the current record's "data_admiss" value
 * @method Titular             setDataExpira()   Sets the current record's "data_expira" value
 * @method Titular             setDataNasc()     Sets the current record's "data_nasc" value
 * @method Titular             setDataRenova()   Sets the current record's "data_renova" value
 * @method Titular             setEstadoCivil()  Sets the current record's "estado_civil" value
 * @method Titular             setSexo()         Sets the current record's "sexo" value
 * @method Titular             setDependentes()  Sets the current record's "Dependentes" collection
 * @method Titular             setAtendimentos() Sets the current record's "Atendimentos" collection
 * 
 * @package    sindhealth
 * @subpackage model
 * @author     Felipe Kaled
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTitular extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('titular');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nome', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('matricula', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 30,
             ));
        $this->hasColumn('data_admiss', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('data_expira', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('data_nasc', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('data_renova', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('estado_civil', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('sexo', 'string', 1, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Dependente as Dependentes', array(
             'local' => 'id',
             'foreign' => 'titular_id'));

        $this->hasMany('Atendimento as Atendimentos', array(
             'local' => 'id',
             'foreign' => 'titular_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}