<?php

/**
 * BaseTelefone
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $numero
 * @property string $tipo
 * @property integer $titular_id
 * @property Titular $Titular
 * 
 * @method integer  getId()         Returns the current record's "id" value
 * @method string   getNumero()     Returns the current record's "numero" value
 * @method string   getTipo()       Returns the current record's "tipo" value
 * @method integer  getTitularId()  Returns the current record's "titular_id" value
 * @method Titular  getTitular()    Returns the current record's "Titular" value
 * @method Telefone setId()         Sets the current record's "id" value
 * @method Telefone setNumero()     Sets the current record's "numero" value
 * @method Telefone setTipo()       Sets the current record's "tipo" value
 * @method Telefone setTitularId()  Sets the current record's "titular_id" value
 * @method Telefone setTitular()    Sets the current record's "Titular" value
 * 
 * @package    sindhealth
 * @subpackage model
 * @author     Felipe Kaled
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTelefone extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('telefone');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('numero', 'string', 12, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 12,
             ));
        $this->hasColumn('tipo', 'string', 12, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 12,
             ));
        $this->hasColumn('titular_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Titular', array(
             'local' => 'titular_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}