<?php

/**
 * BaseAtendimento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $descricao
 * @property integer $titular_id
 * @property integer $tipo
 * @property integer $encaminhamento_id
 * @property integer $sf_guard_user_id
 * @property Titular $Titular
 * @property sfGuardUser $sfGuardUser
 * @property Encaminhamento $Encaminhamento
 * 
 * @method integer        getId()                Returns the current record's "id" value
 * @method string         getDescricao()         Returns the current record's "descricao" value
 * @method integer        getTitularId()         Returns the current record's "titular_id" value
 * @method integer        getTipo()              Returns the current record's "tipo" value
 * @method integer        getEncaminhamentoId()  Returns the current record's "encaminhamento_id" value
 * @method integer        getSfGuardUserId()     Returns the current record's "sf_guard_user_id" value
 * @method Titular        getTitular()           Returns the current record's "Titular" value
 * @method sfGuardUser    getSfGuardUser()       Returns the current record's "sfGuardUser" value
 * @method Encaminhamento getEncaminhamento()    Returns the current record's "Encaminhamento" value
 * @method Atendimento    setId()                Sets the current record's "id" value
 * @method Atendimento    setDescricao()         Sets the current record's "descricao" value
 * @method Atendimento    setTitularId()         Sets the current record's "titular_id" value
 * @method Atendimento    setTipo()              Sets the current record's "tipo" value
 * @method Atendimento    setEncaminhamentoId()  Sets the current record's "encaminhamento_id" value
 * @method Atendimento    setSfGuardUserId()     Sets the current record's "sf_guard_user_id" value
 * @method Atendimento    setTitular()           Sets the current record's "Titular" value
 * @method Atendimento    setSfGuardUser()       Sets the current record's "sfGuardUser" value
 * @method Atendimento    setEncaminhamento()    Sets the current record's "Encaminhamento" value
 * 
 * @package    sindhealth
 * @subpackage model
 * @author     Felipe Kaled
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAtendimento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('atendimento');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('descricao', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('titular_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('tipo', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('encaminhamento_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('sf_guard_user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Titular', array(
             'local' => 'titular_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'sf_guard_user_id',
             'foreign' => 'id'));

        $this->hasOne('Encaminhamento', array(
             'local' => 'encaminhamento_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}