<?php

/**
 * AtendimentoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AtendimentoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AtendimentoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Atendimento');
    }

    public static function getSearchMatriculaQuery($matricula)
    {
      $q = Doctrine_Query::create()
        ->from('Atendimento a')
        ->innerJoin('a.Titular t with t.matricula LIKE \'%' . $matricula . '%');

      return $q;
    }

    public static function getEncaminhamentosByDate($datesQueryFormated)
    {

      $queries = array();
      $queries['encaminhamento'] = Doctrine_Query::create()
        ->from('Atendimento a')
        ->where('a.encaminhamento_id IS NOT NULL')
        ->andWhere('a.created_at >= ?', $datesQueryFormated['start'])
        ->andWhere('a.created_at <= ?', $datesQueryFormated['end']);

      $queries['chartData'] = Doctrine_Query::create()
         ->select("COUNT(*) AS cnt, DATE_FORMAT(created_at, \"%y-%m-%d\") AS my_date")
         ->from("Atendimento a")
         ->where('a.encaminhamento_id IS NOT NULL')
        ->andWhere('a.created_at >= ?', $datesQueryFormated['start'])
        ->andWhere('a.created_at <= ?', $datesQueryFormated['end'])
         ->groupBy("DATE_FORMAT(created_at, \"%y-%m-%d\")");


      return $queries;
    }


}
