<?php

/**
 * EncaminhamentoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EncaminhamentoTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object EncaminhamentoTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Encaminhamento');
  }

  //Set locais do encaminhamento
  static public $locais = array(

      'centro'       => array(
        'endereco'=>'Av. Almirante Barroso, 63 sala 1210 - 12º andar',
        'cep'=>'20031-913',
        'telefone'=>'3903-4011/4102-0504/9713-1470/9312-4222',
        'dentista'=>'Dr. Jivago Yuri'
        ),

      'campo_grande' => array(
        'endereco'=>'Rua Campo Grande, 1096 sala 609',
        'cep'=>'23080-000',
        'telefone'=>'3026-2681',
        'dentista'=>'Dr. Jivago Yuri'
        )

      );

  public function getLocais()
  {
    return self::$locais;
  }

  public function getLocalData($local)
  {
    if(array_key_exists($local, self::$locais))
    {
      return self::$locais[$local];
    }
    else
    {
      return null;
    }
  }

  public function findByIdAndTipo($assocId, $tipo)
  {
    $seisMesesAtras = date('Y-m-d 00:00:00', strtotime("-6 months"));
    $q = $this->createQuery('t')
      ->where('t.assoc_id = ?', $assocId)
      ->andWhere('t.tipo = ?', $tipo)
      ->andWhere('t.created_at >= ?', $seisMesesAtras) ;

    return $q->execute();
  }

  public function findByTitular($titularId)
  {
    $titular = Doctrine_Core::getTable('Titular')->find(array($titularId));
    $dependentes = $titular->getDependentes();
    $result = array();
    $enc_titular = $this->findByIdAndTipo($titularId, sfConfig::get('app_assoc_titular'));
    if(count($enc_titular) > 0)
    {
      $result['titular'] = $enc_titular->getFirst();
    }

    $i_dependente = 1;
    foreach($dependentes as $dependente)
    {
      $enc_dependente = $this->findByIdAndTipo($dependente->getId(), sfConfig::get('app_assoc_dependente'));
      if($enc_dependente->count() > 0)
      {
        $result['dependente' . $i_dependente] = $enc_dependente->getFirst();
        $i_dependente++;
      }
    }

    return $result;

  }
}
