<?php

/**
 * TitularTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TitularTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object TitularTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Titular');
  }

  static public $estadosCivis = array(
      'solteiro' => 'Solteiro',
      'casado' => 'Casado',
      'separado' => 'Separado',
      'divorciado' => 'Divorciado',
      'viuvo' => 'Viúvo',
      );

  public function getEstadosCivis()
  {
    return self::$estadosCivis;
  }

  static public $sexos = array(
      'M' => 'Masculino',
      'F' => 'Feminino',
      );

  public function getSexos()
  {
    return self::$sexos;
  }

  public function getByName($keyword)
  {
    $q = $this->createQuery('t')
      ->where('t.nome like ?', '%' . $keyword . '%');

    return $q->execute();
  }

  public function getByMatricula($keyword)
  {
    $matricula = trim($keyword);
    $mat_size = strlen($matricula);
    if($mat_size < 6)
    {
      $size_compl = 6 - $mat_size;
      $compl = "";
      for($i=0; $i < $size_compl; $i++)
      {
        $compl .= '0';
      }
      $matricula = $compl . $matricula;
    }
    $q = $this->createQuery('t')
      ->where('t.matricula like ?', '%' . $matricula . '%');

    return $q->execute();
  }

}
