<?php

/**
 * Titular
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sindhealth
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Titular extends BaseTitular
{
  public function save(Doctrine_Connection $conn = null)
  {
    if($this->isNew() && !$this->getDataExpira())
    {
      $now = $this->getCreatedAt() ? $this->getDateTimeObject('created_at')->format('U') : time();
      $this->setDataExpira(date('Y-m-d H:i:s', $now + 86400 * sfConfig::get('app_validade_dias')));
    }

    return parent::save($conn);
  }

  public function renewValidade($periodo=false)
  {
      $now = time();

      if($periodo)
      {
        $newdate = date('Y-m-d H:i:s', $now + 86400 * $periodo);
      }else{
        $newdate = date('Y-m-d H:i:s', $now + 86400 * sfConfig::get('app_validade_dias'));
      }
      $this->setDataExpira($newdate);
      $this->setDataRenova(date('Y-m-d',$now));
  }

}
