# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

encaminhamentoSuccess:
  stylesheets:    [visualize.css,visualize-light.css]
  javascripts:    [ excanvas.js, jquery.min.js, visualize.jQuery.js, example.js]

printencaminhamentoSuccess:
  stylesheets:    [visualize.css,visualize-light.css]
  javascripts:    [ excanvas.js, jquery.min.js, visualize.jQuery.js, example.js]
  has_layout:     false


